// import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Layout from "~/components/segments/Layout";
import HeroBanner from "~/components/ui/HeroBanner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <Layout className="mt-[80px]">
          <HeroBanner
            className="min-h-screen bg-gradient-to-b from-neutral-900 from-[95%] to-yellow-400 to-[0%] px-4 text-beige lg:bg-gradient-to-r"
            title="Imagine a place"
            subtitle="Where you'll able to sell courses. Organize Events. Create Groups. Create Forums. Have personalized member profiles. And so much more!"
            ctaLabel="Enroll now"
            ctaLink="https://calendly.com/staxy"
          />
        </Layout>
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
